Fashion/Controllers/GiohangController.cs
using Application;
using Fashion.Models;
using MyDb.Dao;
using MyDb.Entity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Fashion.Controllers
{
    public class GiohangController : Controller
    {
        private const string GiohangSession = "GIOHANG_SESSION";
        // GET: Giohang
        public ActionResult Index()
        {
            var giohang = Session[GiohangSession];
            var list = new List<GiohangItem>();
            if (giohang != null)
            {
                list = (List<GiohangItem>)giohang;
            }
            return View(list);
        }
        public JsonResult DeleteAll()    //xóa tất cả giỏ hàng
        {
            Session[GiohangSession] = null;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult Delete(long id)   //xóa 1 sản phẩm trong giỏ hàng
        {
            var sessionGIOHANG = (List<GiohangItem>)Session[GiohangSession];
            sessionGIOHANG.RemoveAll(x => x.SanPham.Id == id);
            Session[GiohangSession] = sessionGIOHANG;
            return Json(new
            {
                status = true
            });
        }
        public JsonResult Update(string giohangModel)
        {
            var jsonGiohang = new JavaScriptSerializer().Deserialize<List<GiohangItem>>(giohangModel);
            var sessionGIOHANG = (List<GiohangItem>)Session[GiohangSession];

            foreach (var item in sessionGIOHANG)
            {
                var jsonItem = jsonGiohang.SingleOrDefault(x => x.SanPham.Id == item.SanPham.Id);
                if (jsonItem != null)
                {
                    item.Soluong = jsonItem.Soluong;
                }
            }
            Session[GiohangSession] = sessionGIOHANG;
            return Json(new
            {
                status = true
            });
        }
        public ActionResult ThemItem(long sanphamId, int soluong)
        {
            var sanpham = new SanphamDao().ViewDetail(sanphamId);
            var giohang = Session[GiohangSession];
            if (giohang != null)    //nếu giỏ hàng khác null  tức là đã có trong giỏ hàng
            {
                var list = (List<GiohangItem>)giohang;
                if (list.Exists(x => x.SanPham.Id == sanphamId))
                {
                    foreach (var item in list)
                    {
                        if (item.SanPham.Id == sanphamId)
                        {
                            item.Soluong += soluong;
                        }
                    }
                }
                else
                {
                    //tạo mới 1 đối tượng giỏ hàng
                    var item = new GiohangItem();
                    item.SanPham = sanpham;
                    item.Soluong = soluong;
                    list.Add(item);
                }
                //gán vào session
                Session[GiohangSession] = list;

            }
            else   //chưa có trong giỏ hàng
            {
                //tạo mới 1 đối tượng giỏ hàng
                var item = new GiohangItem();
                item.SanPham = sanpham;
                item.Soluong = soluong;
                var list = new List<GiohangItem>();
                list.Add(item);

                //gán vào session
                Session[GiohangSession] = list;
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Thanhtoan()   //hàm thanh toán
        {
            var giohang = Session[GiohangSession];
            var list = new List<GiohangItem>();
            if (giohang != null)
            {
                list = (List<GiohangItem>)giohang;
            }
            return View(list);
        }
        [HttpPost]
        public ActionResult Thanhtoan(string nguoinhan, string sdt, string diachi, string email)   //hàm thanh toán
        {
            var dathang = new DatHang();
            dathang.CreatedDate = DateTime.Now;
            dathang.Shipdiachi = diachi;
            dathang.ShipMobile = sdt;
            dathang.ShipName = nguoinhan;
            dathang.ShipEmail = email;
            try
            {
                var id = new DathangDao().Them(dathang);
                var giohang = (List<GiohangItem>)Session[GiohangSession];
                var detailDao = new DathangDetailDao();
                decimal total = 0;
                foreach (var item in giohang)
                {
                    var dathangDetail = new DatHangDetail();
                    dathangDetail.SanphamId = item.SanPham.Id;
                    dathangDetail.DathangId = id;
                    dathangDetail.DonGia = item.SanPham.Gia;
                    dathangDetail.Soluong = item.Soluong;
                    detailDao.Them(dathangDetail);

                    total += (item.SanPham.Gia.GetValueOrDefault(0) * item.Soluong);
                }
                string content = System.IO.File.ReadAllText(Server.MapPath("~/chung/client/template/neworder.html"));

                content = content.Replace("{{CustomerName}}", nguoinhan);
                content = content.Replace("{{Phone}}", sdt);
                content = content.Replace("{{Email}}", email);
                content = content.Replace("{{Address}}", diachi);
                content = content.Replace("{{Total}}", total.ToString("N0"));
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new Email().guiMail(email, "Đơn hàng mới từ Fashion Shop", content);
                new Email().guiMail(toEmail, "Đơn hàng mới từ Fashion Shop", content);
            }
            catch(Exception ex)
            {
                //hiển thị log
                return Redirect("/error-thanh-toan");
            }
            return Redirect("/thanh-cong");
        }
        public ActionResult Thanhcong()
        {
            return View();
        }
    }
}

Fashion/Views/Giohang/Index.cshtml
@model List<Fashion.Models.GiohangItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section jsFooter{
    <script src="/chung/client/js/controller/giohangController.js"></script>
}
<div class="content">
    <div class="section group">
        @if (Model.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã Sản Phẩm</td>
                        <td>Tên Sản Phẩm</td>
                        <td>Ảnh Sản Phẩm</td>
                        <td>Số Lượng</td>
                        <td>Đơn Giá</td>
                        <td>Thành Tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.SanPham.Id</td>
                            <td>@item.SanPham.Name</td>
                            <td><img src="@item.SanPham.Hinh" width="100" /></td>
                            <td><input type="text" class="txtSoluong" data-id="@item.SanPham.Id" value="@item.Soluong" /></td>
                            <td>@item.SanPham.Gia.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.SanPham.Gia.GetValueOrDefault(0) * item.Soluong).ToString("N0"))</td>
                            <td> <button data-id="@item.SanPham.Id"  class="btnXoa btn btn-danger">Xóa</button> </td>
                        </tr>
                    }
                </tbody>
            </table>

            <button id="btnContinue" class="btn btn-success">Tiếp Tục</button>
            <button id="btnUpdate" class="btn btn-success">Cập Nhật</button>
            <button id="btnDeleteAll" class="btn btn-danger">Xoá Tất Cả</button>
            <button id="btnThanhtoan" class="btn btn-primary">Thanh Toán</button>
        }
        else
        {
            <span class="alert alert-danger">Giỏ Hàng Trống</span>
        }
    </div>
</div>

Fashion/Views/Giohang/Thanhcong.cshtml
@{
    ViewBag.Title = "Thanhcong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="alert alert-success">
   Chúng mừng bạn đã đặt hàng thành công ở shop chúng tôi.
</div>
<div>!Hãy Kiểm Tra Email</div>

Fashion/Views/Giohang/Thanhtoan.cshtml
@model List<Fashion.Models.GiohangItem>
@{
    ViewBag.Title = "Thanh Toán";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="section group">
        @if(Model.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <td>Mã SP</td>
                        <td>Tên SP</td>
                        <td>Ảnh SP</td>
                        <td>Số lượng</td>
                        <td>Đơn giá</td>
                        <td>Thành tiền</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.SanPham.Id</td>
                            <td>@item.SanPham.Name</td>
                            <td><img src="@item.SanPham.Hinh" width="100" /></td>
                            <td><input type="text" class="txtSoluong" data-id="@item.SanPham.Id" value="@item.Soluong" /></td>
                            <td>@item.SanPham.Gia.GetValueOrDefault(0).ToString("N0")</td>
                            <td>@((item.SanPham.Gia.GetValueOrDefault(0) * item.Soluong).ToString("N0"))</td>
                            <td><a href="#" data-id="@item.SanPham.Id" class="btnXoa btn btn-danger">Xoá</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
    <div class="section group">
        <div class="col-md-6">
            @using (Html.BeginForm("Thanhtoan", "Giohang", FormMethod.Post))
            {
                <div class="form-group">
                    <label>Người nhận</label>
                    <input name="nguoinhan" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Điện thoại</label>
                    <input name="sdt" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input name="diachi" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" class="form-control" />
                </div>
                <button type="submit" class="btn btn-success">Đặt Hàng</button>
            }
        </div>

    </div>
</div>