Fashion/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fashion.Areas.Admin.Controllers
{
    public class HomeController : BaseController
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fashion/Controllers/HomeController.cs
using Fashion.Common;
using Fashion.Models;
using MyDb.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fashion.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ViewBag.Slides = new SlideDao().ListAll();
            var sanphamDao = new SanphamDao();
            //lấy ra những sản phẩm mới và hot
            ViewBag.listNewSanphams = sanphamDao.ListNewSanpham(4);
            ViewBag.listHotSanphams = sanphamDao.ListHotSanpham(4);
            return View();
        }
        [ChildActionOnly]  //dành cho 1 cái view ko gọi tới trang khác được
        public ActionResult Menuchung()   //hàm gọi menu
        {
            var model = new MenuDao().ListByGroupId(1);
            return PartialView(model);
        }
        public ActionResult Menutren()   //hàm gọi menu ở trên
        {
            var model = new MenuDao().ListByGroupId(2);
            return PartialView(model);
        }
        public PartialViewResult HeaderGiohang()   //hàm gọi menu giỏ hàng.
        {
            var giohang = Session[CommonParams.GiohangSession];
            var list = new List<GiohangItem>();
            if (giohang != null)
            {
                list = (List<GiohangItem>)giohang;
            }

            return PartialView(list);
        }
        public ActionResult Footer()   //hàm gọi footer
        {
            var model = new FooterDao().GetFooter();
            return PartialView(model);
        }
    }
}

Fashion/Controllers/SanPhamController.cs
using MyDb.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fashion.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult Index()
        {
            return View();
        }
        [ChildActionOnly]
        public PartialViewResult DanhmucSanpham()
        {
            var model = new DanhmucSanphamDao().ListAll();
            return PartialView(model);

        }
        public ActionResult Danhmuc(long dmId, int page= 1, int pageSize = 1)  //truyền ra view danhmuc, phân trang cho sản phẩm
        {
            var danhmuc = new DanhmucDao().ViewDetail(dmId);
            ViewBag.Danhmucs = danhmuc;
            int totalTong = 0;
            var model = new SanphamDao().ListByDanhmucId(dmId, ref totalTong, page, pageSize);

            ViewBag.Total = totalTong;
            ViewBag.Page = page;

            int maxPage = 5;  //số trang tối đa.
            int totalPage = 0; //tổng số trang mặt định 0;

            totalPage = (int)Math.Ceiling((double)(totalTong / pageSize));//làm tròn số trang.
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = maxPage;         // trang cuối cùng
            ViewBag.Next = page + 1;   //trang kế tiếp 
            ViewBag.Prev = page - 1;   // trang trước đó.
             
            return View(model);
        }
        public ActionResult Detail(long spid)   //hàm chi tiết sp , truyền ra view sản phẩm
        {
            var sanpham = new SanphamDao().ViewDetail(spid);
            ViewBag.Danhmucs = new DanhmucSanphamDao().ViewDetail(sanpham.DanhmucId.Value);
            ViewBag.Relatedsp = new SanphamDao().ListHotSanphams(spid);
            return View(sanpham);
        }
    }
}

Fashion/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang Chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var slides = (List<MyDb.Entity.Slide>)ViewBag.Slides;
    var spmoi = (List<MyDb.Entity.SanPham>)ViewBag.listNewSanphams;
    var sphot = (List<MyDb.Entity.SanPham>)ViewBag.listHotSanphams;

}
@section slide
{
    <div class="header_slide">
        <div class="header_bottom_left">
            <div class="categories">
                @{ Html.RenderAction("DanhmucSanpham", "SanPham");}
            </div>
        </div>
        <div class="header_bottom_right">
            <div class="slider">
                <div id="slider">
                    <div id="mover">
                        @foreach (var item in slides)
                        {
                            <div class="slide">
                                <div class="slider-img">
                                    <a href="@item.Link"><img src="@item.Hinh" alt="learn more" /></a>
                                </div>
                                <div class="slider-text">
                                    <h1>Clearance<br><span>SALE</span></h1>
                                    <h2>UPTo 20% OFF</h2>
                                    <div class="features_list">
                                        <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                                    </div>
                                    <a href="preview.html" class="button">Shop Now</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                        }
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Sản Phẩm Mới</h3>
        </div>
        <div class="see">
            <p><a href="/san-pham">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in spmoi)
        {
            var url = "/chi-tiet/" + item.MetaTitle + "-" + item.Id;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@url"><img src="@item.Hinh" alt="@item.Name" /></a>
                <h2>@item.Name</h2>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Gia.HasValue ? item.Gia.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?sanphamId=@item.Id&soluong=1">Thêm vào giỏ</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }
    </div>
    <div class="content_bottom">
        <div class="heading">
            <h3>Sản Phẩm Hot</h3>
        </div>
        <div class="see">
            <p><a href="/san-pham">Xem tất cả</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in sphot)
        {
            var url = "/chi-tiet/" + item.MetaTitle + "-" + item.Id;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@url"><img src="@item.Hinh" alt="@item.Name" /></a>
                <h2>@item.Name</h2>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Gia.HasValue ? item.Gia.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?sanphamId=@item.Id&soluong=1">Thêm vào giỏ</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }
    </div>
</div>